# Generated by Django 3.1.4 on 2021-01-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
    ]
